"""empty message

Revision ID: 039549d7e7ca
Revises: 64b342611fa2
Create Date: 2021-12-22 16:40:30.931866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039549d7e7ca'
down_revision = '64b342611fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_attr_values')
    op.drop_table('product_attrs')
    op.drop_column('product_skus', 'image')
    op.add_column('products', sa.Column('attrs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'attrs')
    op.add_column('product_skus', sa.Column(
        'image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('product_attrs',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('product_attrs_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('product_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['products.id'], name='product_attrs_product_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='product_attrs_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('product_attr_values',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('value', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('image', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('product_attr_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['product_attr_id'], [
                        'product_attrs.id'], name='product_attr_values_product_attr_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='product_attr_values_pkey')
                    )
    # ### end Alembic commands ###
