"""empty message

Revision ID: 1898130e72f1
Revises: 039549d7e7ca
Create Date: 2021-12-22 16:48:43.708794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1898130e72f1'
down_revision = '039549d7e7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_skus', 'image')
    # ### end Alembic commands ###
