"""empty message

Revision ID: 36cbefe1cb04
Revises: 69ce0e5d7aa5
Create Date: 2022-01-04 11:42:23.257426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cbefe1cb04'
down_revision = '69ce0e5d7aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('image', sa.String(), nullable=True))
    op.drop_constraint('order_items_product_sku_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'product_sku_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_sku_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_items_product_sku_id_fkey', 'order_items', 'product_skus', ['product_sku_id'], ['id'])
    op.drop_column('order_items', 'image')
    # ### end Alembic commands ###
