"""empty message

Revision ID: 69ce0e5d7aa5
Revises: c495905f13ae
Create Date: 2021-12-28 21:12:11.366964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ce0e5d7aa5'
down_revision = 'c495905f13ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    # ### end Alembic commands ###
