"""empty message

Revision ID: 9810711e13db
Revises: 1898130e72f1
Create Date: 2021-12-22 21:31:35.825326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9810711e13db'
down_revision = '1898130e72f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
