"""empty message

Revision ID: c495905f13ae
Revises: 9810711e13db
Create Date: 2021-12-26 20:38:59.249783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c495905f13ae'
down_revision = '9810711e13db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_skus_product_id_fkey', 'product_skus', type_='foreignkey')
    op.create_foreign_key(None, 'product_skus', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_skus', type_='foreignkey')
    op.create_foreign_key('product_skus_product_id_fkey', 'product_skus', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
