"""empty message

Revision ID: e1c99a5c5edc
Revises: f9f5ccfa38d6
Create Date: 2021-12-03 13:25:57.726567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c99a5c5edc'
down_revision = 'f9f5ccfa38d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('sort', sa.Integer(), nullable=True))
    op.drop_constraint('categories_pid_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'pid')
    op.drop_column('categories', 'image')
    op.drop_column('categories', 'bg_image')
    op.drop_column('categories', 'bg_color')
    op.drop_column('categories', 'type')
    op.drop_column('categories', 'desc')
    op.drop_constraint('products_category_root_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'category_root_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_root_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_category_root_id_fkey', 'products', 'categories', ['category_root_id'], ['id'])
    op.add_column('categories', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('bg_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('bg_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_pid_fkey', 'categories', 'categories', ['pid'], ['id'])
    op.drop_column('categories', 'sort')
    # ### end Alembic commands ###
