"""empty message

Revision ID: e2bbf2900348
Revises: 36cbefe1cb04
Create Date: 2022-01-05 13:56:28.661707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bbf2900348'
down_revision = '36cbefe1cb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'remarks')
    # ### end Alembic commands ###
